// Mocks generated by Mockito 5.4.4 from annotations
// in movie_tv_level_maximum/test/presentation/pages/tv_show/tv_show_episodes_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_tv_level_maximum/domain/use_cases/tv_show/get_tv_show_episodes.dart'
    as _i2;
import 'package:movie_tv_level_maximum/presentation/bloc/tv_show/episodes/tv_show_episodes_bloc.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvShowEpisodes_0 extends _i1.SmartFake
    implements _i2.GetTvShowEpisodes {
  _FakeGetTvShowEpisodes_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvShowEpisodesState_1 extends _i1.SmartFake
    implements _i3.TvShowEpisodesState {
  _FakeTvShowEpisodesState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvShowEpisodesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowEpisodesBloc extends _i1.Mock
    implements _i3.TvShowEpisodesBloc {
  MockTvShowEpisodesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvShowEpisodes get getTvShowEpisodes => (super.noSuchMethod(
        Invocation.getter(#getTvShowEpisodes),
        returnValue: _FakeGetTvShowEpisodes_0(
          this,
          Invocation.getter(#getTvShowEpisodes),
        ),
      ) as _i2.GetTvShowEpisodes);

  @override
  _i3.TvShowEpisodesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTvShowEpisodesState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.TvShowEpisodesState);

  @override
  _i4.Stream<_i3.TvShowEpisodesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i3.TvShowEpisodesState>.empty(),
      ) as _i4.Stream<_i3.TvShowEpisodesState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i3.TvShowEpisodesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i3.TvShowEpisodesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.TvShowEpisodesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i3.TvShowEpisodesEvent>(
    _i5.EventHandler<E, _i3.TvShowEpisodesState>? handler, {
    _i5.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i5.Transition<_i3.TvShowEpisodesEvent, _i3.TvShowEpisodesState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void onChange(_i5.Change<_i3.TvShowEpisodesState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
