// Mocks generated by Mockito 5.4.4 from annotations
// in movie_tv_level_maximum/test/presentation/pages/tv_show/tv_show_episodes_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:movie_tv_level_maximum/common/state_enum.dart' as _i5;
import 'package:movie_tv_level_maximum/domain/entities/tv_show/tv_show_episode.dart'
    as _i3;
import 'package:movie_tv_level_maximum/domain/use_cases/tv_show/get_tv_show_episodes.dart'
    as _i2;
import 'package:movie_tv_level_maximum/presentation/provider/tv_show/tv_show_episodes_notifier.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvShowEpisodes_0 extends _i1.SmartFake
    implements _i2.GetTvShowEpisodes {
  _FakeGetTvShowEpisodes_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvShowEpisode_1 extends _i1.SmartFake implements _i3.TvShowEpisode {
  _FakeTvShowEpisode_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvShowEpisodesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowEpisodesNotifier extends _i1.Mock
    implements _i4.TvShowEpisodesNotifier {
  MockTvShowEpisodesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvShowEpisodes get getTvShowEpisodes => (super.noSuchMethod(
        Invocation.getter(#getTvShowEpisodes),
        returnValue: _FakeGetTvShowEpisodes_0(
          this,
          Invocation.getter(#getTvShowEpisodes),
        ),
      ) as _i2.GetTvShowEpisodes);

  @override
  _i3.TvShowEpisode get tvShowEpisode => (super.noSuchMethod(
        Invocation.getter(#tvShowEpisode),
        returnValue: _FakeTvShowEpisode_1(
          this,
          Invocation.getter(#tvShowEpisode),
        ),
      ) as _i3.TvShowEpisode);

  @override
  _i5.RequestState get tvShowEpisodeState => (super.noSuchMethod(
        Invocation.getter(#tvShowEpisodeState),
        returnValue: _i5.RequestState.Empty,
      ) as _i5.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> fetchTvShowEpisodes(
    int? id,
    int? season,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTvShowEpisodes,
          [
            id,
            season,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
