// Mocks generated by Mockito 5.4.4 from annotations
// in movie_tv_level_maximum/test/domain/usecases/tv_show/get_list_tv_shows_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_tv_level_maximum/common/failure.dart' as _i5;
import 'package:movie_tv_level_maximum/domain/entities/tv_show/tv_show.dart'
    as _i6;
import 'package:movie_tv_level_maximum/domain/entities/tv_show/tv_show_detail.dart'
    as _i7;
import 'package:movie_tv_level_maximum/domain/entities/tv_show/tv_show_episode.dart'
    as _i8;
import 'package:movie_tv_level_maximum/domain/repositories/tv_show_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvShowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowRepository extends _i1.Mock implements _i3.TvShowRepository {
  MockTvShowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>
      getAiringTodayTvShow() => (super.noSuchMethod(
            Invocation.method(
              #getAiringTodayTvShow,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.TvShow>>(
              this,
              Invocation.method(
                #getAiringTodayTvShow,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>> getOnTheAirTvShow() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvShow,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.TvShow>>(
          this,
          Invocation.method(
            #getOnTheAirTvShow,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>> getPopularTvShow() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvShow,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.TvShow>>(
          this,
          Invocation.method(
            #getPopularTvShow,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>> getTopRatedTvShow() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvShow,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.TvShow>>(
          this,
          Invocation.method(
            #getTopRatedTvShow,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.TvShowDetail>> getTvShowDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvShowDetail,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.TvShowDetail>>.value(
                _FakeEither_0<_i5.Failure, _i7.TvShowDetail>(
          this,
          Invocation.method(
            #getTvShowDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.TvShowDetail>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>
      getTvShowRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvShowRecommendations,
              [id],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.TvShow>>(
              this,
              Invocation.method(
                #getTvShowRecommendations,
                [id],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>> searchTvShows(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvShows,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.TvShow>>(
          this,
          Invocation.method(
            #searchTvShows,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlistTvShow(
          _i7.TvShowDetail? tvShow) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlistTvShow,
          [tvShow],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlistTvShow,
            [tvShow],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWatchlistTvShow(
          _i7.TvShowDetail? tvShow) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTvShow,
          [tvShow],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlistTvShow,
            [tvShow],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<bool> isAddedToWatchlistTvShow(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlistTvShow,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>> getWatchlistTvShow() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvShow,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.TvShow>>(
          this,
          Invocation.method(
            #getWatchlistTvShow,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TvShow>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.TvShowEpisode>> getAllEpisodes(
    int? id,
    int? season,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEpisodes,
          [
            id,
            season,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.TvShowEpisode>>.value(
                _FakeEither_0<_i5.Failure, _i8.TvShowEpisode>(
          this,
          Invocation.method(
            #getAllEpisodes,
            [
              id,
              season,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.TvShowEpisode>>);
}
