name: Flutter CI

on:
  push:
    branches:
      - develop
      - feature/workflows
      - main
  pull_request:
    branches:
      - develop
      - feature/workflows
      - main

jobs:
  install_dependencies:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1  # Menggunakan versi v1

      - name: Install dependencies
        run: flutter pub get

  run_tests:
    runs-on: windows-latest
    needs: install_dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
