name: Flutter CI

on:
  push:
    branches:
      - develop
      - feature/workflows
      - main
  pull_request:
    branches:
      - develop
      - feature/workflows
      - main

jobs:
  install_dependencies:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1  # Menggunakan versi v1

      - name: Install dependencies
        run: flutter pub get

      # Run build app
      - name: Build APK
        run: flutter build apk --no-sound-null-safety
