name: Flutter CI

on:
  push:
    branches:
      - develop
      - feature/workflows
      - main
  pull_request:
    branches:
      - develop
      - feature/workflows
      - main

jobs:
  install_dependencies:
    runs-on: windows-latest

    steps:
      # Checkout code from repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Version Flutter
      
      # Run Flutter pub get for download dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run build app
      - name: Build APK
        run: flutter build apk --no-sound-null-safety
