name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          cache: true

      # Cache Flutter dependencies
      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.os }}-flutter-cache
            .pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk --no-sound-null-safety

      # Run tests
      - name: Run tests
        run: flutter test
